# Generated by Django 3.1.7 on 2021-03-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end',
            field=models.TimeField(verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start',
            field=models.TimeField(verbose_name='Start'),
        ),
    ]
