# Generated by Django 3.1.7 on 2021-03-17 15:48

from django.db import migrations, models
import django.db.models.manager
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210315_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('concealed', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=20)),
                ('text', django_quill.fields.QuillField()),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'data',
                'default_manager_name': 'data',
            },
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'base_manager_name': 'data', 'default_manager_name': 'data', 'get_latest_by': 'created', 'ordering': ['-created'], 'verbose_name': 'Buchung', 'verbose_name_plural': 'Buchungen'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'base_manager_name': 'data', 'default_manager_name': 'data', 'get_latest_by': 'created', 'ordering': ['-created'], 'verbose_name': 'Zeitslot', 'verbose_name_plural': 'Zeitslots'},
        ),
    ]
