# Generated by Django 3.1.7 on 2021-03-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20210317_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='accepted',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'neu'), ('accepted', 'bestätigt'), ('rejected', 'abgelehnt')], default='new', max_length=10),
        ),
    ]
