# Generated by Django 3.1.7 on 2021-03-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20210318_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.timeslot'),
        ),
    ]
